"""
Example:
Suppose we want to  two company A and B:
Both has same three sector a,b,c and 
it's generate net profit margin rate. 
How can we compare this two company using mean?
"""
import  numpy as np
from scipy.stats import gmean

##  net profit margin rate generated by a,b,c sector.
A=[0.4,0.5,0.8]  
B=[0.2,0.9,0.6]

print("geometric mean of A:",gmean(A))
print("geometric mean of A:",gmean(B))

print("##############")

print("arithmetic mean of A:",np.mean(A))
print("airthmetic mean of A:",np.mean(B))

'''
output:
geometric mean of A: 0.5428835233189813
geometric mean of A: 0.47622031559045985
##############
arithmetic mean of A: 0.5666666666666668
airthmetic mean of A: 0.5666666666666668

conclusion : 
arithmetic mean is the same in both cases
but the geometric mean is different so 
choosing the right mean for a given case 
gives us the right comparison.
'''